version: '3.8'
services:
  fefilm:
    container_name: fefilm
    image: mysql:8.0
    command: mysqld --sql_mode=""
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=FeFilm
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
